# Generated by Django 5.0.7 on 2024-07-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='category',
            name='engname',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='category',
            name='rusname',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(max_length=3),
        ),
    ]
