# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: streaming.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'streaming.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fstreaming.proto\x12\x0fstring_analyzer\"\'\n\x11StreamDataRequest\x12\x12\n\ninput_text\x18\x01 \x01(\t\"2\n\x12StreamDataResponse\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\t2m\n\x10StreamingService\x12Y\n\nStreamData\x12\".string_analyzer.StreamDataRequest\x1a#.string_analyzer.StreamDataResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'streaming_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STREAMDATAREQUEST']._serialized_start=36
  _globals['_STREAMDATAREQUEST']._serialized_end=75
  _globals['_STREAMDATARESPONSE']._serialized_start=77
  _globals['_STREAMDATARESPONSE']._serialized_end=127
  _globals['_STREAMINGSERVICE']._serialized_start=129
  _globals['_STREAMINGSERVICE']._serialized_end=238
# @@protoc_insertion_point(module_scope)
