# unary_grpc_calculator/unary_pb2.py

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: unary.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'unary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bunary.proto\x12\ncalculator\"Z\n\x12\x43\x61lculationRequest\x12\x0c\n\x04num1\x18\x01 \x01(\x02\x12\x0c\n\x04num2\x18\x02 \x01(\x02\x12(\n\toperation\x18\x03 \x01(\x0e\x32\x15.calculator.Operation\"<\n\x13\x43\x61lculationResponse\x12\x0e\n\x06result\x18\x01 \x01(\x02\x12\x15\n\rerror_message\x18\x02 \x01(\t*<\n\tOperation\x12\x07\n\x03\x41\x44\x44\x10\x00\x12\x0c\n\x08SUBTRACT\x10\x01\x12\x0c\n\x08MULTIPLY\x10\x02\x12\n\n\x06\x44IVIDE\x10\x03\x32\\\n\nCalculator\x12N\n\tCalculate\x12\x1e.calculator.CalculationRequest\x1a\x1f.calculator.CalculationResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'unary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPERATION']._serialized_start=181
  _globals['_OPERATION']._serialized_end=241
  _globals['_CALCULATIONREQUEST']._serialized_start=27
  _globals['_CALCULATIONREQUEST']._serialized_end=117
  _globals['_CALCULATIONRESPONSE']._serialized_start=119
  _globals['_CALCULATIONRESPONSE']._serialized_end=179
  _globals['_CALCULATOR']._serialized_start=243
  _globals['_CALCULATOR']._serialized_end=335
# @@protoc_insertion_point(module_scope)
