# Generated by Django 5.0.7 on 2024-08-01 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_book_autor_name_alter_book_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='title',
        ),
    ]
