"""
Django settings for money_convert_django project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8_@1ov_-h1dn58ti=2bg3e_n#i4i5z*!eb0puvd90z!r1w^v*o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
########################################################################################################################
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    "debug_toolbar",  # Приложение для отладочной панели Django Debug Toolbar
    'converter',
]
########################################################################################################################

########################################################################################################################
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Промежуточное ПО для интеграции отладочной панели Django Debug Toolbar в проект.
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]
########################################################################################################################

ROOT_URLCONF = 'money_convert_django.urls'

########################################################################################################################
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Задаем директории, в которых будут искаться шаблоны.
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
########################################################################################################################
WSGI_APPLICATION = 'money_convert_django.wsgi.application'


# Database
########################################################################################################################
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
########################################################################################################################

# Password validation
########################################################################################################################
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
########################################################################################################################

# Настройки интернационализации и локализации в Django.
########################################################################################################################
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'ru-Ru'    # Код языка для сайта, указывающий на русский язык и его региональные особенности.
TIME_ZONE = 'Europe/Kiev'  # Часовой пояс сайта, установленный на время Киева в Европе.
USE_I18N = True            # Указывает на необходимость использования интернационализации для поддержки различных языков
USE_TZ = True              # Указывает на использование часовых поясов в приложении, используя заданный TIME_ZONE.
########################################################################################################################


# Настройка статических и медиафайлов (CSS, JavaScript, Images)
########################################################################################################################
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# URL-путь для обслуживания статических файлов на веб-сайте.
STATIC_URL = '/static/'

# Директория, куда будут собираться статические файлы для развертывания веб-сайта.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Дополнительные директории, где Django будет искать статические файлы.
STATICFILES_DIRS = [BASE_DIR / 'static',]

# Директория, где будут сохраняться загруженные медиафайлы (изображения, видео и т.д.).
MEDIA_ROOT = BASE_DIR / 'media'

# URL-путь для доступа к загруженным медиафайлам на веб-сайте.
MEDIA_URL = '/media/'
########################################################################################################################

# Список внутренних IP-адресов, с которых будет доступен отладочный панель.
########################################################################################################################
INTERNAL_IPS: list[str] = [
    # Добавляем локальный IP-адрес, который обычно используется при разработке на локальной машине.
    "127.0.0.1",
    # Дополнительные IP-адреса могут быть добавлены сюда по мере необходимости.
]
########################################################################################################################

# Тип поля первичного ключа по умолчанию
########################################################################################################################
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
########################################################################################################################

# Настройки кэша для Django
########################################################################################################################
CACHES = {
    'default': {
        # Использование локального кэша в памяти
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}
########################################################################################################################