"""Fix

Revision ID: df4b2e1f7aec
Revises: 58e563fc1e2a
Create Date: 2025-02-27 18:37:35.507051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df4b2e1f7aec'
down_revision: Union[str, None] = '58e563fc1e2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('cache_expires_at', sa.DateTime(), nullable=True))
    op.alter_column('posts', 'text',
               existing_type=sa.VARCHAR(length=1048576),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_constraint('posts_user_id_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('tokens', sa.Column('token_type', sa.String(length=50), nullable=True))
    op.add_column('tokens', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('tokens', sa.Column('is_jwt', sa.Boolean(), nullable=True))
    op.drop_constraint('tokens_user_id_fkey', 'tokens', type_='foreignkey')
    op.create_foreign_key(None, 'tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tokens', type_='foreignkey')
    op.create_foreign_key('tokens_user_id_fkey', 'tokens', 'users', ['user_id'], ['id'])
    op.drop_column('tokens', 'is_jwt')
    op.drop_column('tokens', 'created_at')
    op.drop_column('tokens', 'token_type')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_user_id_fkey', 'posts', 'users', ['user_id'], ['id'])
    op.alter_column('posts', 'text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1048576),
               existing_nullable=False)
    op.drop_column('posts', 'cache_expires_at')
    # ### end Alembic commands ###
