services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: k2_erp
      POSTGRES_USER: k2_user
      POSTGRES_PASSWORD: k2_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U k2_user -d k2_erp"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: ["sh", "entrypoint.prod.sh"]   # Gunicorn
    environment:
      DJANGO_ENV: production
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    # volumes отсутствуют – код внутри образа!

volumes:
  postgres_data: