"""Create initial database schema

Revision ID: 063c5e3c783c
Revises: 
Create Date: 2025-08-05 17:04:46.641992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '063c5e3c783c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arbitrage_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('coin', sa.String(length=10), nullable=False),
    sa.Column('buy_exchange', sa.String(length=20), nullable=False),
    sa.Column('sell_exchange', sa.String(length=20), nullable=False),
    sa.Column('planned_amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('trade_value_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('spread_percent', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('status', sa.Enum('EXECUTION_FAILED', 'EXECUTED_UNPROFITABLE', 'FULLY_SUCCESSFUL', name='arbitragestatus'), nullable=False),
    sa.Column('failure_reason', sa.String(length=100), nullable=True),
    sa.Column('balance_issues', sa.Text(), nullable=True),
    sa.Column('buy_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('sell_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('actual_profit_usd', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arbitrage_attempts_status'), 'arbitrage_attempts', ['status'], unique=False)
    op.create_index(op.f('ix_arbitrage_attempts_timestamp'), 'arbitrage_attempts', ['timestamp'], unique=False)
    op.create_index(op.f('ix_arbitrage_attempts_user_id'), 'arbitrage_attempts', ['user_id'], unique=False)
    op.create_table('system_states',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('user_coins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('coin_ticker', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'coin_ticker', name='_user_coin_uc')
    )
    op.create_index(op.f('ix_user_coins_user_id'), 'user_coins', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='_user_setting_uc')
    )
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_user_coins_user_id'), table_name='user_coins')
    op.drop_table('user_coins')
    op.drop_table('system_states')
    op.drop_index(op.f('ix_arbitrage_attempts_user_id'), table_name='arbitrage_attempts')
    op.drop_index(op.f('ix_arbitrage_attempts_timestamp'), table_name='arbitrage_attempts')
    op.drop_index(op.f('ix_arbitrage_attempts_status'), table_name='arbitrage_attempts')
    op.drop_table('arbitrage_attempts')
    # ### end Alembic commands ###
