# Generated by Django 4.2.11 on 2024-06-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=3000, verbose_name='Текст комментария'),
        ),
    ]
