"""
Django settings for portfolio_master project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from django.contrib.messages import constants as messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*shrt0@vr^f*5@^_!&ldk!aq3nm+)#n4yr5iijn!)&$*un^%zg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'portfolio.apps.PortfolioConfig',
    'debug_toolbar',                      # Приложение для отладочной панели Django Debug Toolbar
    'django_ckeditor_5',  # Приложение для интеграции редактора CKEditor 5 с Django

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Промежуточное ПО для интеграции отладочной панели Django Debug Toolbar в проект.
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'portfolio_master.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'portfolio_master.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Настройки интернационализации и локализации в Django.
########################################################################################################################
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'ru-Ru'    # Код языка для сайта, указывающий на русский язык и его региональные особенности.
TIME_ZONE = 'Europe/Kiev'  # Часовой пояс сайта, установленный на время Киева в Европе.
USE_I18N = True            # Указывает на необходимость использования интернационализации для поддержки различных языков
USE_TZ = True              # Указывает на использование часовых поясов в приложении, используя заданный TIME_ZONE.
########################################################################################################################


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MESSAGE_TAGS = {
        messages.DEBUG: 'alert-secondary',
        messages.INFO: 'alert-info',
        messages.SUCCESS: 'alert-success',
        messages.WARNING: 'alert-warning',
        messages.ERROR: 'alert-danger',
}

# Настройки для CKEditor
########################################################################################################################
# Определяем настраиваемую цветовую палитру для редактора
customColorPalette = [
    {
        'color': 'hsl(4, 90%, 58%)',    # Красный цвет
        'label': 'Red'                  # Метка цвета
    },
    {
        'color': 'hsl(340, 82%, 52%)',  # Розовый цвет
        'label': 'Pink'                 # Метка цвета
    },
    {
        'color': 'hsl(291, 64%, 42%)',   # Фиолетовый цвет
        'label': 'Purple'                # Метка цвета
    },
    {
        'color': 'hsl(262, 52%, 47%)',   # Темно-фиолетовый цвет
        'label': 'Deep Purple'           # Метка цвета
    },
    {
        'color': 'hsl(231, 48%, 48%)',  # Индиго
        'label': 'Indigo'               # Метка цвета
    },
    {
        'color': 'hsl(207, 90%, 54%)',  # Синий цвет
        'label': 'Blue'                 # Метка цвета
    },
]

CKEDITOR_5_CUSTOM_CSS = 'path_to.css'                    # Путь к пользовательскому CSS (необязательно)
# CKEDITOR_5_FILE_STORAGE = 'storage_app.CustomStorage'  # Путь к пользовательскому хранилищу файлов (необязательно)

# Конфигурация CKEditor
CKEDITOR_5_CONFIGS = {
    'default': {                                                                   # Конфигурация по умолчанию
        'toolbar': ['heading', '|', 'bold', 'italic', 'link',
                    'bulletedList', 'numberedList', 'blockQuote', 'imageUpload'],  # Инструменты на панели
    },
    'extends': {                                              # Расширенная конфигурация
        'blockToolbar': [
            'paragraph', 'heading1', 'heading2', 'heading3',  # Блоки заголовков и параграфов
            '|',
            'bulletedList', 'numberedList',                   # Списки
            '|',
            'blockQuote',                                     # Цитата
        ],
        # Полный набор инструментов на панели
        'toolbar': ['heading', '|', 'outdent', 'indent', '|', 'bold', 'italic', 'link', 'underline', 'strikethrough',
                    'code', 'subscript', 'superscript', 'highlight', '|', 'codeBlock', 'sourceEditing', 'insertImage',
                    'bulletedList', 'numberedList', 'todoList', '|', 'blockQuote', 'imageUpload', '|',
                    'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', 'mediaEmbed', 'removeFormat',
                    'insertTable'],
        'image': {  # Конфигурация для изображений
            'toolbar': ['imageTextAlternative', '|', 'imageStyle:alignLeft',
                        'imageStyle:alignRight', 'imageStyle:alignCenter', 'imageStyle:side', '|'],
            # Панель инструментов для изображений
            'styles': [
                'full',         # Полный размер
                'side',         # Боковая
                'alignLeft',    # Выровнять влево
                'alignRight',   # Выровнять вправо
                'alignCenter',  # Выровнять по центру
            ]
        },
        'table': {  # Конфигурация для таблиц
            'contentToolbar': ['tableColumn', 'tableRow', 'mergeTableCells',
                               'tableProperties', 'tableCellProperties'],
            # Панель инструментов для таблиц
            'tableProperties': {
                'borderColors': customColorPalette,     # Настраиваемые цвета границ таблиц
                'backgroundColors': customColorPalette  # Настраиваемые цвета фона таблиц
            },
            'tableCellProperties': {
                'borderColors': customColorPalette,     # Настраиваемые цвета границ ячеек таблиц
                'backgroundColors': customColorPalette  # Настраиваемые цвета фона ячеек таблиц
            }
        },
        'heading': {  # Конфигурация для заголовков
            'options': [
                # Параграф
                {'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph'},
                # Заголовок 1
                {'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1'},
                # Заголовок 2
                {'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2'},
                # Заголовок 3
                {'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3'}
            ]
        }
    },
    'list': {                      # Конфигурация для списков
        'properties': {
            'styles': 'true',      # Разрешить стили для списков
            'startIndex': 'true',  # Разрешить изменение начального индекса списков
            'reversed': 'true',    # Разрешить изменение порядка списков на обратный
        }
    }
}