# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import recommendations_pb2 as recommendations__pb2

GRPC_GENERATED_VERSION = '1.66.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in recommendations_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RecommendationsStub(object):
    """Определение gRPC сервиса под названием Recommendations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Recommend = channel.unary_unary(
                '/recommendations.Recommendations/Recommend',
                request_serializer=recommendations__pb2.RecommendationRequest.SerializeToString,
                response_deserializer=recommendations__pb2.RecommendationResponse.FromString,
                _registered_method=True)


class RecommendationsServicer(object):
    """Определение gRPC сервиса под названием Recommendations
    """

    def Recommend(self, request, context):
        """Определяем метод Recommend, который является унарным RPC методом
        Этот метод принимает RecommendationRequest и возвращает RecommendationResponse
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecommendationsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Recommend': grpc.unary_unary_rpc_method_handler(
                    servicer.Recommend,
                    request_deserializer=recommendations__pb2.RecommendationRequest.FromString,
                    response_serializer=recommendations__pb2.RecommendationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'recommendations.Recommendations', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('recommendations.Recommendations', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Recommendations(object):
    """Определение gRPC сервиса под названием Recommendations
    """

    @staticmethod
    def Recommend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendations.Recommendations/Recommend',
            recommendations__pb2.RecommendationRequest.SerializeToString,
            recommendations__pb2.RecommendationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
