# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recommendations.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'recommendations.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15recommendations.proto\x12\x0frecommendations\"n\n\x15RecommendationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12/\n\x08\x63\x61tegory\x18\x02 \x01(\x0e\x32\x1d.recommendations.BookCategory\x12\x13\n\x0bmax_results\x18\x03 \x01(\x05\"/\n\x12\x42ookRecommendation\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\"V\n\x16RecommendationResponse\x12<\n\x0frecommendations\x18\x01 \x03(\x0b\x32#.recommendations.BookRecommendation*?\n\x0c\x42ookCategory\x12\x0b\n\x07MYSTERY\x10\x00\x12\x13\n\x0fSCIENCE_FICTION\x10\x01\x12\r\n\tSELF_HELP\x10\x02\x32o\n\x0fRecommendations\x12\\\n\tRecommend\x12&.recommendations.RecommendationRequest\x1a\'.recommendations.RecommendationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recommendations_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOKCATEGORY']._serialized_start=291
  _globals['_BOOKCATEGORY']._serialized_end=354
  _globals['_RECOMMENDATIONREQUEST']._serialized_start=42
  _globals['_RECOMMENDATIONREQUEST']._serialized_end=152
  _globals['_BOOKRECOMMENDATION']._serialized_start=154
  _globals['_BOOKRECOMMENDATION']._serialized_end=201
  _globals['_RECOMMENDATIONRESPONSE']._serialized_start=203
  _globals['_RECOMMENDATIONRESPONSE']._serialized_end=289
  _globals['_RECOMMENDATIONS']._serialized_start=356
  _globals['_RECOMMENDATIONS']._serialized_end=467
# @@protoc_insertion_point(module_scope)
