//
// Created by Shrekulka on 17.10.2023.
//



#ifndef TCP_CLIENT_FOR_DETERMINING_TIME_AND_DATE_SOCKET_H
#define TCP_CLIENT_FOR_DETERMINING_TIME_AND_DATE_SOCKET_H




#endif //TCP_CLIENT_FOR_DETERMINING_TIME_AND_DATE_SOCKET_H
