# client_streaming_average_calculator/client_streaming_pb2_grpc.py

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import client_streaming_pb2 as client__streaming__pb2

GRPC_GENERATED_VERSION = '1.66.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in client_streaming_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AverageCalculatorStub(object):
    """Сервис для вычисления среднего значения
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalculateAverage = channel.stream_unary(
                '/average_calculator.AverageCalculator/CalculateAverage',
                request_serializer=client__streaming__pb2.NumberRequest.SerializeToString,
                response_deserializer=client__streaming__pb2.AverageResponse.FromString,
                _registered_method=True)


class AverageCalculatorServicer(object):
    """Сервис для вычисления среднего значения
    """

    def CalculateAverage(self, request_iterator, context):
        """Метод для клиентского потокового RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AverageCalculatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalculateAverage': grpc.stream_unary_rpc_method_handler(
                    servicer.CalculateAverage,
                    request_deserializer=client__streaming__pb2.NumberRequest.FromString,
                    response_serializer=client__streaming__pb2.AverageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'average_calculator.AverageCalculator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('average_calculator.AverageCalculator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AverageCalculator(object):
    """Сервис для вычисления среднего значения
    """

    @staticmethod
    def CalculateAverage(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/average_calculator.AverageCalculator/CalculateAverage',
            client__streaming__pb2.NumberRequest.SerializeToString,
            client__streaming__pb2.AverageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
