# client_streaming_average_calculator/client_streaming_pb2.py

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: client_streaming.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'client_streaming.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63lient_streaming.proto\x12\x12\x61verage_calculator\"\x1f\n\rNumberRequest\x12\x0e\n\x06number\x18\x01 \x01(\x01\"\"\n\x0f\x41verageResponse\x12\x0f\n\x07\x61verage\x18\x01 \x01(\x01\x32s\n\x11\x41verageCalculator\x12^\n\x10\x43\x61lculateAverage\x12!.average_calculator.NumberRequest\x1a#.average_calculator.AverageResponse\"\x00(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client_streaming_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NUMBERREQUEST']._serialized_start=46
  _globals['_NUMBERREQUEST']._serialized_end=77
  _globals['_AVERAGERESPONSE']._serialized_start=79
  _globals['_AVERAGERESPONSE']._serialized_end=113
  _globals['_AVERAGECALCULATOR']._serialized_start=115
  _globals['_AVERAGECALCULATOR']._serialized_end=230
# @@protoc_insertion_point(module_scope)
