# Generated by Django 5.1.1 on 2024-09-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_name', models.CharField(choices=[('get_device_info', 'Get Device Info'), ('get_gwp_info', 'Get GWP Info'), ('get_sim_info', 'Get SIM Info')], max_length=50)),
                ('device_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
