# Generated by Django 5.1.1 on 2024-09-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Информация об устройстве',
                'verbose_name_plural': 'Информация об устройствах',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GwpInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Информация о GWP',
                'verbose_name_plural': 'Информация о GWP',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SimInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Информация о SIM',
                'verbose_name_plural': 'Информация о SIM',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ManagementCommand',
        ),
    ]
