# Generated by Django 5.0.7 on 2024-07-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='conversionhistory',
            index=models.Index(fields=['from_currency', 'to_currency', 'conversion_date'], name='converter_c_from_cu_d68f11_idx'),
        ),
    ]
